sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js: stable
cache:
  yarn: true
  directories:
    - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g flow-typed
script:
- flow-typed install -s=true
- npm run serve &
- npm test
after_success:
- npm run codecov
notifications:
  email: false
  slack:
    secure: UezGkysrUTr0vgq/uttIyGLB8ENu4Ifmdu+9nHWR+WoZmmY8BGAR7EGiya/dn6jbzGhWeVZtFTMdQSfIwApT14eEVRT6Vjmi+TtDaVCXj6e2EtertO+Dd/cJro9/T1l9RYYSKooQggKh6CovhjqbNCuDQLNBmHG6IKg3jYqabZfApsLw00BRDgn1SzVnrWLbdXeZouzSJIUfPCsCSgSe230BFTQIKlfnStg8zvcc3wlCvTYdxyOQsUp5KQmct5LXBPJ4+YbBSsSW/pXAj9MyymCSHWEma699wDePua9WayZsh3moUg5pmcdUTFhMXrH4FeBlz57dmYZLja0WBLiz3lP1F+TAMq7b/U/dx8Pb8mMOaWCwLYcm20ITAfbrnKWGfqxlaLCAGdwfNO3NjAYzOhGRRzNCId1IQw/5VyG1s5xNcYM/w6VJJYKm/i4Ieb4v/ZMn9IDcdetMlN5g8kVZLklmmYLpMTsqm+uzyU0y05K6xbV1qlXIQ0air4Vnn5RNDoDU8g92cXpE9fubgXtg5O8jiDzZUWviMTwFZL6dgUa2x+Gu/xDeuYrSDLI49GpqHtfNWnswPf3u8pIUe2Fd/CJn+4bz18Ov+teIiolfFkiPcEIeqYq0/QKNcOvaVeMFNf6YiHbBpN6M99expSMu7L4p1DFJJf23TqSu45eBso0=
