codecov:
  bot: userdivebot
  token: b5dc7cee-69b5-4694-a1a6-50210299a52a

coverage:
  precision: 2
  round: down
  range: "80...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
