codecov:
  bot: userdivebot
  token: 06a832b7-2139-4b4f-a9c9-cf7d6292b997

coverage:
  precision: 2
  round: down
  range: "80...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
